import type { Metadata } from "next";
import { Button } from "@/components/Button";
import { Container } from "@/components/Container";
import { Hero } from "@/components/Hero";
import { NoticeBox } from "@/components/NoticeBox";
import { siteConfig } from "@/lib/site";
export const metadata: Metadata = { title: "Contact", description: "Contact Digital Economy Institute for partnerships, research collaboration, media, communities, and discovery/IP inquiries." };
const inquiryTypes = ["Partnership inquiry","Research collaboration","Media inquiry","Community membership inquiry","Discovery/IP inquiry"];
export default function ContactPage() {
  return <><Hero title="Contact" subtitle="Contact the Digital Economy Institute for research collaboration, partnerships, media, communities, and discovery/IP inquiries."/><section className="bg-paper py-16"><Container className="grid gap-8 lg:grid-cols-[.7fr_.3fr]"><form className="rounded-3xl border border-line bg-white p-6 shadow-subtle"><div className="grid gap-5 md:grid-cols-2"><label className="block text-sm font-semibold">Name<input type="text" className="mt-2 w-full rounded-xl border border-line px-4 py-3 text-sm outline-none focus:border-ink"/></label><label className="block text-sm font-semibold">Email<input type="email" className="mt-2 w-full rounded-xl border border-line px-4 py-3 text-sm outline-none focus:border-ink"/></label></div><label className="mt-5 block text-sm font-semibold">Inquiry type<select className="mt-2 w-full rounded-xl border border-line bg-white px-4 py-3 text-sm outline-none focus:border-ink">{inquiryTypes.map(t => <option key={t}>{t}</option>)}</select></label><label className="mt-5 block text-sm font-semibold">Message<textarea rows={7} className="mt-2 w-full rounded-xl border border-line px-4 py-3 text-sm outline-none focus:border-ink"/></label><div className="mt-6"><Button type="button">Send message</Button></div><div className="mt-5"><NoticeBox>Contact form is a frontend prototype. Production use requires secure form handling, spam protection, and email or CRM integration.</NoticeBox></div></form><aside className="space-y-5"><div className="rounded-3xl border border-line bg-white p-6 shadow-subtle"><p className="text-xs font-bold uppercase tracking-[.2em] text-steel">Institutional email</p><p className="mt-3 text-sm font-semibold">{siteConfig.email}</p><p className="mt-3 text-sm leading-6 text-steel">Placeholder email. Replace with a verified institutional address before public launch.</p></div>{inquiryTypes.map(t => <div key={t} className="rounded-2xl border border-line bg-white p-4 text-sm font-semibold shadow-subtle">{t}</div>)}</aside></Container></section></>;
}
