import type { Metadata } from "next";
import { Container } from "@/components/Container";
import { Hero } from "@/components/Hero";
import { NoticeBox } from "@/components/NoticeBox";
import { SectionHeading } from "@/components/SectionHeading";
export const metadata: Metadata = { title: "Targeted AI", description: "Targeted AI — A Web4 Infrastructure for Transparent and Reproducible Computational Research." };
const architecture = ["Public research interface","Collaborative research workspaces","AI analytical agents","Validation and trust layer","Data integration infrastructure","Open-source governance"];
export default function TargetedAIPage() {
  return <><Hero eyebrow="Central project" title="Targeted AI" subtitle="A Web4 Infrastructure for Transparent and Reproducible Computational Research.">Targeted AI is a research infrastructure concept designed to make computational research more transparent, reliable, reproducible, and useful for evidence-based policymaking.</Hero><section className="bg-white py-16"><Container className="space-y-14"><SectionHeading title="What is Targeted AI?"><p>Targeted AI proposes a structured environment where datasets, assumptions, analytical workflows, AI-assisted checks, and expert validation are documented together. The goal is not to replace researchers, but to make research processes more inspectable and reusable.</p></SectionHeading><div className="grid gap-6 lg:grid-cols-2">{[
["Why computational research needs new infrastructure","Many computational analyses are difficult to reproduce because data sources, transformations, parameters, and decision points are not documented in a consistent way."],
["Web4 infrastructure for research integrity","The Web4 framing emphasizes trust, provenance, verification, auditability, and human accountability."],
["AI-assisted research validation","AI can help flag anomalies, summarize evidence, identify missing assumptions, and suggest validation questions. These functions remain subject to human expert review."],
["Transparent analytical workflows","A workflow should show what data was used, how it was transformed, which assumptions were selected, which model outputs were generated, and who reviewed the analysis."],
["Hybrid AI-human validation","The platform concept combines automated checks with domain communities and expert review. AI systems support human experts and do not replace human judgment."],
["Data provenance and audit trails","Data provenance records the origin, transformation, and reuse of data. Audit trails help reviewers understand how a conclusion was produced."]
].map(([title,text]) => <Info key={title} title={title} text={text}/>)}</div><SectionHeading title="Difference from conventional repositories"><p>Conventional repositories store files and metadata. Targeted AI is designed as an active research validation system: it connects datasets, methods, analytical steps, AI-supported checks, community review, and publication pathways.</p></SectionHeading><div><SectionHeading title="Platform architecture"/><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{architecture.map(item => <div key={item} className="rounded-2xl border border-line bg-paper p-6"><h3 className="text-lg font-bold">{item}</h3><p className="mt-2 text-sm leading-6 text-steel">Backend-ready component for secure data handling, permissions, and transparent governance.</p></div>)}</div></div><div className="grid gap-6 lg:grid-cols-2"><Info title="Open-source governance and GNU GPL model" text="GNU GPL-style logic can help protect public-interest infrastructure, preserve openness in derivative work, and support transparent community development."/><Info title="Ethical considerations" text="AI systems may reflect biased or incomplete data. Sensitive data should not be uploaded without secure infrastructure and governance."/><Info title="Expected impact" text="Targeted AI aims to strengthen evidence-based policymaking, reproducible science, research communication, and cross-sector collaboration."/><Info title="Discovery vault and intellectual property pathway" text="Discovery Vaults can document discoveries and prepare selected ideas for expert review, WIPO pathways, and submission to the Intellectual Property Office of Armenia."/></div><NoticeBox tone="warning">This MVP presents Targeted AI as a frontend and content architecture. Production implementation requires backend infrastructure, authentication, secure storage, audit logs, model integrations, expert governance, and legal review workflows.</NoticeBox></Container></section></>;
}
function Info({ title, text }: { title: string; text: string }) { return <div className="rounded-3xl border border-line bg-white p-6 shadow-subtle"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-3 text-sm leading-7 text-steel">{text}</p></div>; }
