export type IssueArea = {
  title: string;
  slug: string;
  description: string;
  whyItMatters: string;
  policyRelevance: string;
  targetedAiConnection: string;
  relatedCommunity?: string;
};

export const issueAreas: IssueArea[] = [
  ["Digital Economy","digital-economy","Institutional, technical, and policy foundations for digital transformation.","Digital transformation changes how governments, firms, universities, and citizens produce and use knowledge.","Governments need reliable infrastructure, interoperable data systems, and governance models that support public trust.","Targeted AI treats the digital economy as an evidence system, not only as a market for software tools."],
  ["Targeted AI","targeted-ai","AI-assisted analytical infrastructure for transparent and reproducible research workflows.","AI outputs are useful only when assumptions, data sources, and validation steps can be examined.","Public decisions require traceable evidence rather than opaque automation.","This is the institute’s central project and research infrastructure concept."],
  ["Web4 Infrastructure","web4-infrastructure","Trust-oriented infrastructure for provenance, identity, verification, and accountable digital collaboration.","Future knowledge systems need mechanisms for trust, auditability, and human accountability.","Web4 concepts can help public institutions design transparent and verifiable digital services.","Targeted AI applies Web4 logic to research workflows, community validation, and data provenance."],
  ["Research Integrity","research-integrity","Methods and governance that make research more transparent, reproducible, and accountable.","Weak documentation and unverifiable analysis can undermine scientific and policy decisions.","Research integrity is a public-sector requirement when evidence supports regulation, funding, or programs.","The Targeted AI validation layer is designed around documented assumptions and expert review."],
  ["Data Provenance","data-provenance","Tracking data origin, transformation, analytical steps, and responsible reuse.","Without provenance, users cannot know whether data is current, reliable, or appropriate for a decision.","Data provenance supports audits, public accountability, and cross-institutional data sharing.","Targeted AI places provenance records inside analytical workflows."],
  ["AI Governance","ai-governance","Rules, practices, and evaluation systems for responsible use of AI in institutions.","AI systems may reflect data limitations, design choices, and institutional bias.","AI governance helps institutions use AI without weakening rights, safety, or accountability.","The platform includes human review, transparency notices, and validation checkpoints."],
  ["Computational Science","computational-science","Research methods that use computation, models, datasets, and simulation to generate knowledge.","Computational work is only credible when workflows and assumptions are reproducible.","Computational evidence increasingly shapes health, agriculture, climate, and legal policy.","Targeted AI documents computational workflows and supports expert validation."],
  ["Open Source Infrastructure","open-source-infrastructure","Transparent software and governance models for public-interest digital tools.","Open systems improve inspectability, reuse, and institutional learning.","Public institutions can reduce vendor lock-in and improve transparency through open infrastructure.","The project is framed around open-source governance and GNU GPL logic."],
  ["Public Sector Innovation","public-sector-innovation","Digital transformation practices for governments and public institutions.","Policy problems require reliable systems, not isolated technology pilots.","Public-sector innovation must align with capacity, procurement, accountability, and citizen trust.","Targeted AI supports evidence systems for public programs and institutional decisions."],
  ["Agriculture and Food Systems","agriculture-and-food-systems","Digital tools, data, and research communities for agriculture and food resilience.","Agricultural decisions depend on weather, soil, water, inputs, markets, and expert knowledge.","Governments can use evidence to improve rural productivity, resilience, and food security.","The Agriculture Community validates domain-specific data and practical tools.","Agriculture Community"],
  ["Healthcare and Biomedical Research","healthcare-and-biomedical-research","Responsible digital tools and evidence systems for health research and clinical support.","Healthcare evidence must be carefully reviewed because decisions affect human wellbeing.","Health policy needs validated research, privacy protections, and expert oversight.","The Healthcare Community uses AI only as an expert-support tool, not as a medical authority.","Healthcare Community"],
  ["Environment and Climate Data","environment-and-climate-data","Data-driven approaches to environmental monitoring, climate risk, and pollution analysis.","Environmental systems require longitudinal, local, and cross-sectoral evidence.","Climate and pollution policy depends on accurate measurement and transparent reporting.","The Environment Community can test data provenance and monitoring workflows.","Environment Community"],
  ["Law, Compliance, and Digital Governance","law-compliance-and-digital-governance","Digital tools for legal analysis, compliance, and institutional governance.","Legal and policy decisions require careful interpretation and human expert judgment.","Transparent legal workflows can support better drafting, comparison, and compliance monitoring.","The Jurisprudence Community explores legal analysis calculators as research tools.","Jurisprudence Community"],
  ["AI & Blockchain Governance","ai-blockchain-governance","Responsible frameworks for AI, blockchain, provenance, and smart contract ecosystems.","Blockchain and AI systems can create trust benefits only when governance is clear.","Public institutions need careful evaluation before adopting decentralized or AI-enabled tools.","The AI & Blockchain Community examines Web4 readiness and data provenance tools.","AI & Blockchain Community"],
  ["Intellectual Property and Innovation Protection","intellectual-property-and-innovation-protection","Research workflows for protecting discoveries, technical ideas, and invention pathways.","Researchers and entrepreneurs need safe ways to document ideas before public disclosure.","Clear IP pathways can help institutions translate research into public and economic value.","The Discovery Vault concept provides a pathway to expert review, WIPO, and national IP institutions."]
].map(([title, slug, description, whyItMatters, policyRelevance, targetedAiConnection, relatedCommunity]) => ({ title, slug, description, whyItMatters, policyRelevance, targetedAiConnection, relatedCommunity })) as IssueArea[];

export function getIssueAreaBySlug(slug: string) {
  return issueAreas.find((i) => i.slug === slug);
}
